### ISSUE TITLE
Personal secret support

### ISSUE THREAD

**Issue by zifeo** [zifeo/lade#104]
If in a few situations (e.g. gitlab token access for terraform management), lade should load a different secret per user yet the usage/scope/access of the token should remain the same. The idea is to add a `lade user` to register a user, save it using something similar to [this](https://docs.rs/appconfig/latest/appconfig/) and support the following syntax. If the user is not set, lade should recommend to run first `lade user set`.

```
^tofu:
  SAME_SECRET_FOR_EVERYONE: infisical://app.infisical.com/63a2290a0edf8bf1f65e3784/dev/INFISICAL_A
  TF_HTTP_USERNAME:
    zifeo: infisical://app.infisical.com/63a2290a0edf8bf1f65e3784/dev/INFISICAL_B
    alex: infisical://app.infisical.com/63a2290a0edf8bf1f65e3784/dev/INFISICAL_C
  TF_HTTP_PASSWORD: ...
```
